FROM --platform=linux/amd64 node:20-slim AS builder
WORKDIR /app
ARG NPM_TOKEN
COPY server/package*.json server/.npmrc ./
RUN npm ci
RUN rm -f .npmrc
COPY server/ .
RUN npm run build

FROM --platform=linux/amd64 node:20-slim
WORKDIR /app
ARG NPM_TOKEN
COPY --from=builder /app/dist ./dist
COPY server/package*.json server/.npmrc ./
RUN npm ci --omit=dev && npm cache clean --force && rm -f .npmrc
EXPOSE 5000
CMD ["node", "dist/index.js"]
