FROM node:20-alpine AS builder
WORKDIR /app
ARG NPM_TOKEN
COPY server/package*.json server/.npmrc ./
RUN npm ci
RUN rm -f .npmrc
COPY server/ .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY server/package*.json ./
RUN npm ci --omit=dev
EXPOSE 5000
CMD ["node", "dist/index.js"]
