import ExcelJS from 'exceljs';
import { IReconciliationMonthDocument } from '../models/ReconciliationMonth.model';
import { IInvoiceRow } from '../models/ReconciliationMonth.model';

// ─── Colour constants (matching existing Python tool) ─────────────────────────

const COLORS = {
  darkBlue: '1F3864',
  midBlue: '2E75B6',
  lightBlue: 'D6E4F0',
  grey: 'F2F2F2',
  paleBlue: 'EBF3FA',
  greenBg: 'E2EFDA',
  greenText: '375623',
  orangeBg: 'FEF3DC',
  orangeText: '8B4513',
  redBg: 'FFDAD9',
  redText: '833535',
  white: 'FFFFFF',
  black: '000000',
} as const;

type ColorKey = keyof typeof COLORS;

function fill(hex: string): ExcelJS.Fill {
  return { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${hex}` } };
}

function font(color: string, bold = false, size = 10): Partial<ExcelJS.Font> {
  return { color: { argb: `FF${color}` }, bold, size };
}

function border(): Partial<ExcelJS.Borders> {
  const side = { style: 'thin' as const, color: { argb: 'FFD0D0D0' } };
  return { top: side, left: side, bottom: side, right: side };
}

function headerCell(
  row: ExcelJS.Row,
  col: number,
  value: string,
  bgKey: ColorKey = 'darkBlue',
): void {
  const cell = row.getCell(col);
  cell.value = value;
  cell.fill = fill(COLORS[bgKey]);
  cell.font = font(COLORS.white, true);
  cell.alignment = { vertical: 'middle', wrapText: true };
  cell.border = border();
}

function dataCell(
  row: ExcelJS.Row,
  col: number,
  value: ExcelJS.CellValue,
  bgKey: ColorKey = 'white',
  textKey: ColorKey = 'black',
  bold = false,
): void {
  const cell = row.getCell(col);
  cell.value = value;
  cell.fill = fill(COLORS[bgKey]);
  cell.font = font(COLORS[textKey], bold);
  cell.alignment = { vertical: 'middle', wrapText: true };
  cell.border = border();
}

// ─── Strip HTML to plain text, preserving list items as bullets ───────────────

function htmlToPlainText(html: string): string {
  return html
    .replace(/<li>/gi, '• ')
    .replace(/<\/li>/gi, '\n')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<p>/gi, '')
    .replace(/<\/p>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&nbsp;/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

// ─── Format CAD currency ──────────────────────────────────────────────────────

function cad(n: number): string {
  return `$${n.toFixed(2)}`;
}

// ─── Action badge ─────────────────────────────────────────────────────────────

function actionLabel(action: string): string {
  switch (action) {
    case 'no_change': return '✅ No Change';
    case 'additional_charge': return '🔶 Additional Charge';
    case 'credit_memo': return '🔴 Credit Memo';
    default: return '⏳ Awaiting Data';
  }
}

function actionColors(action: string): { bg: ColorKey; text: ColorKey } {
  switch (action) {
    case 'no_change': return { bg: 'greenBg', text: 'greenText' };
    case 'additional_charge': return { bg: 'orangeBg', text: 'orangeText' };
    case 'credit_memo': return { bg: 'redBg', text: 'redText' };
    default: return { bg: 'grey', text: 'black' };
  }
}

// ─── INSTRUCTIONS sheet ───────────────────────────────────────────────────────

function buildInstructionsSheet(wb: ExcelJS.Workbook): void {
  const ws = wb.addWorksheet('INSTRUCTIONS');
  ws.getColumn(1).width = 80;

  const titleRow = ws.addRow(['Evoke Sync — Reconciliation Export Instructions']);
  titleRow.getCell(1).fill = fill(COLORS.darkBlue);
  titleRow.getCell(1).font = font(COLORS.white, true, 14);
  titleRow.height = 30;

  ws.addRow([]);
  ws.addRow(['1. Review each practitioner tab for their billed vs actual hours.']);
  ws.addRow(['2. Credit memos (🔴) and additional charges (🔶) require action in QBO.']);
  ws.addRow(['3. Copy the QBO Description string from the session group rows into QBO.']);
  ws.addRow(['4. The SUMMARY tab shows all practitioners consolidated with totals.']);
  ws.addRow([]);
  ws.addRow(['This workbook was generated by Evoke Sync and is read-only.']);
}

// ─── NOTES sheet ─────────────────────────────────────────────────────────────

function buildNotesSheet(wb: ExcelJS.Workbook, doc: IReconciliationMonthDocument): void {
  const ws = wb.addWorksheet('📋 NOTES');
  ws.getColumn(1).width = 80;

  const titleRow = ws.addRow([`Billing Notes — ${doc.month} ${doc.year}`]);
  titleRow.getCell(1).fill = fill(COLORS.midBlue);
  titleRow.getCell(1).font = font(COLORS.white, true, 12);
  titleRow.height = 25;

  ws.addRow([]);

  const plainText = htmlToPlainText(doc.billingNotesHtml || '(No billing notes entered)');
  const notesRow = ws.addRow([plainText]);
  notesRow.getCell(1).alignment = { wrapText: true, vertical: 'top' };
  notesRow.height = Math.max(60, plainText.split('\n').length * 15);
}

// ─── Per-practitioner sheet ───────────────────────────────────────────────────

const PRAC_COLS = [
  'Invoice #', 'Client', 'Service Type', 'Insurance?',
  'Hrs Billed', 'Rate', 'Amt Billed',
  'Actual Hrs', 'Actual Amt', 'Delta', 'Action',
  'Session Groups', 'QBO Description', 'Notes',
];

function buildPractitionerSheet(
  wb: ExcelJS.Workbook,
  practitioner: string,
  invoices: IInvoiceRow[],
): void {
  const safeName = practitioner.slice(0, 31); // Excel sheet name limit
  const ws = wb.addWorksheet(safeName);

  const colWidths = [10, 22, 22, 10, 9, 8, 10, 9, 10, 10, 18, 30, 55, 30];
  colWidths.forEach((w, i) => { ws.getColumn(i + 1).width = w; });

  // Title row
  const titleRow = ws.addRow([`${practitioner} — ${invoices[0] ? `${invoices[0].practitioner}` : practitioner}`]);
  ws.mergeCells(`A${titleRow.number}:N${titleRow.number}`);
  titleRow.getCell(1).fill = fill(COLORS.darkBlue);
  titleRow.getCell(1).font = font(COLORS.white, true, 12);
  titleRow.height = 25;

  // Header row
  const hRow = ws.addRow(PRAC_COLS);
  PRAC_COLS.forEach((_, i) => headerCell(hRow, i + 1, PRAC_COLS[i], 'midBlue'));
  hRow.height = 20;

  for (const inv of invoices) {
    const { bg, text } = actionColors(inv.action);

    // Session groups as readable string
    const sgText = inv.sessionGroups
      .map((sg) => `${sg.sessionLength}min: ${sg.sessionDates.join(', ')}`)
      .join('\n');
    const descText = inv.sessionGroups.map((sg) => sg.qboDescription).join('\n\n');

    const r = ws.addRow([
      inv.invoiceNo,
      inv.clientName,
      inv.serviceType,
      inv.isInsurance ? 'Yes' : 'No',
      inv.hoursBilled,
      cad(inv.rate),
      cad(inv.amountBilled),
      inv.actualHours,
      cad(inv.actualAmount),
      cad(inv.delta),
      actionLabel(inv.action),
      sgText,
      descText,
      inv.notes,
    ]);

    // Colour the action cell
    const actionCell = r.getCell(11);
    actionCell.fill = fill(COLORS[bg]);
    actionCell.font = font(COLORS[text], true);
    actionCell.border = border();

    // Style all other cells
    for (let c = 1; c <= 14; c++) {
      if (c === 11) continue;
      const cell = r.getCell(c);
      cell.fill = fill(COLORS.paleBlue);
      cell.font = font(COLORS.black);
      cell.alignment = { vertical: 'top', wrapText: true };
      cell.border = border();
    }

    r.height = Math.max(20, (inv.sessionGroups.length * 2 + 1) * 15);
  }

  // Totals row
  const totalBilled = invoices.reduce((s, i) => s + i.amountBilled, 0);
  const totalActual = invoices.reduce((s, i) => s + i.actualAmount, 0);
  const totalDelta = totalActual - totalBilled;

  const totRow = ws.addRow([
    'TOTALS', '', '', '',
    '', '', cad(totalBilled),
    '', cad(totalActual), cad(Math.round(totalDelta * 100) / 100),
    '', '', '', '',
  ]);
  for (let c = 1; c <= 14; c++) {
    totRow.getCell(c).fill = fill(COLORS.lightBlue);
    totRow.getCell(c).font = font(COLORS.darkBlue, true);
    totRow.getCell(c).border = border();
  }
}

// ─── SUMMARY sheet ────────────────────────────────────────────────────────────

function buildSummarySheet(
  wb: ExcelJS.Workbook,
  doc: IReconciliationMonthDocument,
  invoices: IInvoiceRow[],
  supervisorDetails: string,
): void {
  const ws = wb.addWorksheet('✅ SUMMARY');
  const colWidths = [22, 10, 22, 10, 8, 10, 10, 10, 18];
  colWidths.forEach((w, i) => { ws.getColumn(i + 1).width = w; });

  const titleRow = ws.addRow([`${doc.month} ${doc.year} — Reconciliation Summary`]);
  ws.mergeCells(`A${titleRow.number}:I${titleRow.number}`);
  titleRow.getCell(1).fill = fill(COLORS.darkBlue);
  titleRow.getCell(1).font = font(COLORS.white, true, 14);
  titleRow.height = 30;

  const cols = ['Practitioner', 'Invoice #', 'Client', 'Service Type', 'Rate', 'Amt Billed', 'Actual Amt', 'Delta', 'Action'];
  const hRow = ws.addRow(cols);
  cols.forEach((_, i) => headerCell(hRow, i + 1, cols[i], 'midBlue'));

  let grandBilled = 0;
  let grandActual = 0;

  for (const inv of invoices) {
    const { bg, text } = actionColors(inv.action);
    const r = ws.addRow([
      inv.practitioner,
      inv.invoiceNo,
      inv.clientName,
      inv.serviceType,
      cad(inv.rate),
      cad(inv.amountBilled),
      cad(inv.actualAmount),
      cad(inv.delta),
      actionLabel(inv.action),
    ]);

    for (let c = 1; c <= 9; c++) {
      const cell = r.getCell(c);
      cell.fill = fill(c === 9 ? COLORS[bg] : COLORS.paleBlue);
      cell.font = font(c === 9 ? COLORS[text] : COLORS.black, c === 9);
      cell.alignment = { vertical: 'middle' };
      cell.border = border();
    }

    grandBilled += inv.amountBilled;
    grandActual += inv.actualAmount;
  }

  const grandDelta = Math.round((grandActual - grandBilled) * 100) / 100;
  const totRow = ws.addRow([
    'GRAND TOTAL', '', '', '', '',
    cad(Math.round(grandBilled * 100) / 100),
    cad(Math.round(grandActual * 100) / 100),
    cad(grandDelta), '',
  ]);
  for (let c = 1; c <= 9; c++) {
    totRow.getCell(c).fill = fill(COLORS.lightBlue);
    totRow.getCell(c).font = font(COLORS.darkBlue, true);
    totRow.getCell(c).border = border();
  }

  // Sign-off block
  ws.addRow([]);
  ws.addRow([]);
  const signRow = ws.addRow(['Approved by:', doc.approvedBy ?? '']);
  signRow.getCell(1).font = font(COLORS.black, true);
  ws.addRow(['Date:', doc.approvedAt ? doc.approvedAt.toLocaleDateString('en-CA') : '']);
  ws.addRow(['Supervising Clinician:', supervisorDetails]);
}

// ─── Main export function ─────────────────────────────────────────────────────

export async function generateReconciliationExcel(
  doc: IReconciliationMonthDocument,
  supervisorDetails: string,
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Evoke Sync';
  wb.created = new Date();

  buildInstructionsSheet(wb);
  buildNotesSheet(wb, doc);

  // Group invoices by practitioner — excluded invoices are omitted from the export
  const activeInvoices = doc.invoices.filter((inv) => !inv.excluded);
  const byPractitioner = new Map<string, IInvoiceRow[]>();
  for (const inv of activeInvoices) {
    if (!byPractitioner.has(inv.practitioner)) {
      byPractitioner.set(inv.practitioner, []);
    }
    byPractitioner.get(inv.practitioner)!.push(inv);
  }

  for (const [practitioner, invoices] of byPractitioner.entries()) {
    buildPractitionerSheet(wb, practitioner, invoices);
  }

  buildSummarySheet(wb, doc, activeInvoices, supervisorDetails);

  const buffer = await wb.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
